Devel: adds abbott generation
arfc/pride pull request #19
Opened 2020-02-03 15:46 UTC by samgdotson

Closes #18 by generating a typical time history for abbott generation.

2020-02-03 18:08 UTC, samgdotson commented
Closes #20 by adding synthetic histories

2020-02-03 18:44 UTC, robfairh requested changes
See minor comments. The rest looks good.

2020-02-03 18:44 UTC, robfairh commented on data_processing/abbott_generation.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABJ4AAAMJCAYAAABC1/yfAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8
I think this is not the actual demand, but the output power of abbot.

2020-02-03 18:44 UTC, robfairh commented on data_processing/abbott_generation.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABJ4AAAMJCAYAAABC1/yfAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8
Same comment as before.

2020-02-04 17:43 UTC, robfairh commented
Looks good

2020-02-04 17:43 UTC, merged