adds a folder for the ANS abstract and the latex template
arfc/pride pull request #5
Opened 2019-12-26 13:15 UTC by samgdotson

Closes issue #4 

Added a folder that holds the ANS abstract. Template was pulled from 2018-chee-predicting-ans.

2020-01-13 20:36 UTC, robfairh requested changes
I believe the files "dotson-sizing-ans.fdb_latexmk" and "ans-abs/dotson-sizing-ans.fls" are not necessary. If that is the case delete them.

2020-01-13 21:02 UTC, samgdotson commented
You are correct, they are unnecessary files.

Thanks for catching that!

2020-01-14 22:24 UTC, robfairh approved these changes

2020-01-14 22:24 UTC, robfairh commented
LGTM!

2020-01-14 22:25 UTC, merged