Adds final draft of ANS Abstract
arfc/pride pull request #71
Opened 2020-07-02 05:18 UTC by samgdotson

This PR adds the final draft of the abstract I submitted for the ANS Annual Meeting

2020-07-06 20:18 UTC, datw0258 commented on publications/abstracts/reservoir-computing-abs/background.tex
> +usual evening minimum around 40 MW. Weekdays have peaks near 50MW and are
Do you want to have a space between the number and unit? I think either could work (50MW or 50 MW) as long as you are consistent.

2020-07-06 20:23 UTC, datw0258 commented on publications/abstracts/reservoir-computing-abs/background.tex
> +evolution a laminar flame front up to seven Lyapunov
Should it read "...evolution **of** a laminar flame front..." ?

2020-07-06 20:28 UTC, datw0258 requested changes
Looks good! Just a few minor comments

2020-07-27 19:56 UTC, samgdotson commented
@datw0258 could you go ahead and merge this. The deadline is long passed.

2020-08-05 14:38 UTC, merged